---
apiVersion: v1
kind: Service
metadata:
  name: apollo
  labels:
    app: apollo
spec:
  type: NodePort
  selector:
    app: apollo
  ports:
  - port: 30670
    nodePort: 30670
    targetPort: 8070
    name: apollo-portal
  - port: 30680
    nodePort: 30680
    targetPort: 8080
    name: apollo-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
  labels:
    app: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      containers:
      - name: single-all-in-apollo
        image: landykingdom/single-all-in-apollo:0.1
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        env:
          - name: CONFIG_DB_HOST_PORT
            value: 192.168.50.72:3306
          - name: CONFIG_DB_USER
            value: root
          - name: CONFIG_DB_PASS
            value: "123456"
          - name: PORTAL_DB_HOST_PORT
            value: 192.168.50.72:3306
          - name: PORTAL_DB_USER
            value: root
          - name: PORTAL_DB_PASS
            value: "123456"
        ports:
        - containerPort: 8070
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8070
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8070
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5